// Generated by CoffeeScript 1.12.7
var Layer, Promise, Request, Response, Type, __DEV__, createServer, createTrustProxy, default404, default500, etag, getPort, now, onFinish, onRequest, onTimeout, qs, setProto, type;

setProto = require("setProto");

Promise = require("Promise");

Type = require("Type");

now = require("performance-now");

qs = require("querystring");

createServer = require("./utils/createServer");

Response = require("../response");

Request = require("../request");

Layer = require("./Layer");

createTrustProxy = require("./utils/createTrustProxy");

etag = require("./utils/etag");

__DEV__ = process.env.NODE_ENV !== "production";

type = Type("Application");

type.defineArgs({
  port: Number,
  secure: Boolean,
  getContext: Function,
  maxHeaders: Number,
  timeout: Number,
  onError: Function
});

type.defineValues(function(options) {
  return {
    port: getPort(options),
    settings: Object.create(null),
    _layer: Layer(),
    _server: createServer(options, onRequest.bind(this)),
    _timeout: options.timeout,
    _onError: options.onError || default500
  };
});

type.initInstance(function() {
  this.set("trust proxy", false);
  this.set("subdomain offset", 2);
});

onRequest = function(req, res) {
  var app, parts;
  app = this;
  req.startTime = now();
  parts = req.url.split("?");
  req.path = parts[0];
  req.query = qs.parse(parts[1]);
  setProto(req.query, Object.prototype);
  req.app = app;
  req.res = res;
  setProto(req, Request);
  res.app = app;
  res.req = req;
  setProto(res, Response);
  req.next = default404.bind(req, res);
  if (app._timeout > 0) {
    req.setTimeout(onTimeout, app._timeout);
  }
  return app._layer["try"](req, res).then(function() {
    if (!res.finished) {
      return onFinish(res);
    }
  }).then(function() {
    if (req.reading) {
      req.destroy();
    }
    if (res.statusCode !== 408) {
      return app.emit("response", req, res);
    }
  }).fail(function(error) {
    app._onError(error, res);
    return app.emit("response", req, res);
  });
};

type.defineMethods({
  get: function(name) {
    return this.settings[name];
  },
  set: function(name, value) {
    if (arguments.length === 1) {
      return this.settings[name];
    }
    this.settings[name] = value;
    switch (name) {
      case "etag":
        this.set("etag fn", etag.compile(value));
        break;
      case "trust proxy":
        this.set("trust proxy fn", createTrustProxy(value));
    }
  },
  use: function(fn) {
    this._layer.use(fn);
    return this;
  },
  pipe: function(fn) {
    this._layer.pipe(fn);
    return this;
  },
  drain: function(fn) {
    this._layer.drain(fn);
    return this;
  },
  on: function(eventId, handler) {
    this._server.on(eventId, handler);
    return this;
  },
  emit: function(eventId) {
    switch (arguments.length) {
      case 1:
        this._server.emit(eventId);
        break;
      case 2:
        this._server.emit(eventId, arguments[1]);
        break;
      default:
        this._server.emit(eventId, arguments[1], arguments[2]);
    }
    return this;
  },
  ready: function(callback) {
    if (this._server.listening) {
      callback();
    } else {
      this._server.once("listening", callback);
    }
    return this;
  },
  close: function(callback) {
    if (callback) {
      this._server.once("close", callback);
    }
    this._server.close();
    return this;
  },
  _send: function(req, res) {
    return onRequest.call(this, req, res);
  }
});

type.defineStatics({
  Layer: Layer
});

module.exports = type.build();

getPort = function(options) {
  var port;
  if (!(port = options.port)) {
    if (!(port = parseInt(process.env.PORT))) {
      port = options.secure ? 443 : 8000;
    }
    options.port = port;
  }
  return port;
};

onFinish = function(res) {
  var deferred;
  deferred = Promise.defer();
  res.on("finish", deferred.resolve);
  res.on("error", deferred.reject);
  return deferred.promise;
};

onTimeout = function(req, res) {
  res.status(408);
  res.send({
    error: "Request timed out"
  });
  this.emit("response", req, res);
};

default404 = function(res) {
  res.status(404);
  res.send({
    error: "Nothing exists here. Sorry!"
  });
};

default500 = function(error, res) {
  this.emit("requestError", error);
  res.status(500);
  res.send({
    error: "Something went wrong on our end. Sorry!"
  });
};
