// Generated by CoffeeScript 2.2.3
var createTrustProxy, emptyFunction, proxyaddr;

emptyFunction = require("emptyFunction");

proxyaddr = require("proxy-addr");

createTrustProxy = function(value) {
  var value_t;
  value_t = typeof value;
  if (value_t === "function") {
    return value;
  }
  if (value === true) {
    return emptyFunction.thatReturnsTrue;
  }
  if (value === false) {
    return emptyFunction.thatReturnsFalse;
  }
  // Support trusting 'hop count'
  if (value_t === "number") {
    return function(a, i) {
      return i < value;
    };
  }
  // Support comma-separated values
  if (value_t === "string") {
    value = value.split(/\s*,\s*/);
  }
  return proxyaddr.compile(value || []);
};

module.exports = createTrustProxy;
