// Generated by CoffeeScript 1.12.7
var createServer;

createServer = function(options, handler) {
  var server;
  server = options.secure ? (function() {
    var config, fs, getContext, path;
    config = {};
    if (getContext = options.getContext) {
      config.SNICallback = function(hostname, done) {
        return done(null, getContext(hostname));
      };
    } else {
      fs = require("fs");
      path = require("path");
      config.key = fs.readFileSync(path.resolve("ssl.key"), "utf8");
      config.cert = fs.readFileSync(path.resolve("ssl.crt"), "utf8");
    }
    return require("https").createServer(config, handler);
  })() : require("http").createServer(handler);
  server.maxHeadersCount = options.maxHeaders || 50;
  server.listen(options.port);
  return server;
};

module.exports = createServer;
