// Generated by CoffeeScript 1.12.4
var createServer, http, https;

createServer = function(options, handler) {
  var server;
  server = options.secure ? https(handler) : http(handler);
  server.maxHeadersCount = options.maxHeaders || 50;
  server.listen(options.port);
  return server;
};

http = function(handler) {
  return require("http").createServer(handler);
};

https = function(handler) {
  var cert, fs, key, path;
  fs = require("fs");
  path = require("path");
  key = fs.readFileSync(path.resolve("ssl.key"), "utf8");
  cert = fs.readFileSync(path.resolve("ssl.crt"), "utf8");
  return require("https").createServer({
    key: key,
    cert: cert
  }, handler);
};

module.exports = createServer;
