// Generated by CoffeeScript 2.2.3
var createServer;

createServer = function(opts, handler) {
  var server;
  server = opts.secure ? (function() {
    var config, fs, getContext, path;
    config = {};
    if (getContext = opts.getContext) {
      config.SNICallback = function(hostname, done) {
        return done(null, getContext(hostname));
      };
    } else {
      fs = require("fs");
      path = require("path");
      config.key = fs.readFileSync(path.resolve("ssl.key"), "utf8");
      config.cert = fs.readFileSync(path.resolve("ssl.crt"), "utf8");
    }
    return require("https").createServer(config, handler);
  })() : require("http").createServer(handler);
  server.maxHeadersCount = opts.maxHeaders;
  server.listen(opts.path || opts.port);
  return server;
};

module.exports = createServer;
