// Generated by CoffeeScript 1.12.4
var createTrustProxy, emptyFunction, isValid, proxyaddr;

emptyFunction = require("emptyFunction");

proxyaddr = require("proxy-addr");

isValid = require("isValid");

createTrustProxy = function(value) {
  if (typeof value === "function") {
    return value;
  }
  if (value === true) {
    return emptyFunction.thatReturnsTrue;
  }
  if (value === false) {
    return emptyFunction.thatReturnsFalse;
  }
  if (isValid(value, "number")) {
    return function(a, i) {
      return i < value;
    };
  }
  if (isValid(value, "string")) {
    value = value.split(/\s*,\s*/);
  }
  return proxyaddr.compile(value || []);
};

module.exports = createTrustProxy;
