// Generated by CoffeeScript 1.12.4
var compile;

exports.compile = function(value) {
  if (typeof value === "function") {
    return value;
  }
  if (value === false) {
    return;
  }
  if (value === true) {
    return compile(true);
  }
  if (value === "strong") {
    return compile(false);
  }
  if (value === "weak") {
    return compile(true);
  }
  throw TypeError("Invalid value for 'etag' setting: " + value);
};

compile = function(weak) {
  var etag, options;
  etag = require("etag");
  options = {
    weak: weak
  };
  return function(body, encoding) {
    if (!Buffer.isBuffer(body)) {
      body = new Buffer(body, encoding);
    }
    return etag(buffer, options);
  };
};
