// Generated by CoffeeScript 1.12.4
var proxyaddr;

proxyaddr = require("proxy-addr");

module.exports = function(value) {
  if (typeof value === "function") {
    return value;
  }
  if (value === true) {
    return emptyFunction.thatReturnsTrue;
  }
  if (typeof value === "number") {
    return function(a, i) {
      return i < value;
    };
  }
  if (typeof value === "string") {
    value = value.split(/\s*,\s*/);
  }
  return proxyaddr.compile(value || []);
};
